name = "BoundedStreams"
uuid = "819c7365-da23-433e-86d1-f9a07e67aad6"
authors = ["Klaus Crusius <klaus.crusius@web.de>"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
